### ISSUE TITLE
customCheck signature messed up

### ISSUE THREAD

**Issue by mrft** [katholiek-onderwijs-vlaanderen/sri4node-security-api#18]
@eznibe 
This is a mess. There used to be a function
`customCheck: function (tx, sriRequest, ability, resource, component)` that worked like all sri4node functions: tx and sriRequest are ALWAYS the first params.

Now without any notice you changed this function entirely: new params, the order changed + the function probably even does something different. WHY? There are other people using this plugin you know... 

+ No trace of any of this in release notes or README.md.

Stefan's suggestion is to restore customCheck to what it was before (he needs it, and make sure he gets' informed)
And then expose your new function as checkPermissionOnElements(tx, sriRequest, elements, operation, component)

Component seems to be an optional parameter, OPTIONAL params are always put LAST.

It all went wrong in this commit: 
```
eznibe committed on 17 Oct
1 parent f526d19 commit 14693b2536953e362a86ed68f4d12f3154472363
```

```
    [-] customCheck: function (tx, sriRequest, ability, resource, component) {
    [+] customCheck: function (component, tx, sriRequest, elements, operation) {
        ...
        [-] return security.customCheck(tx, sriRequest, ability, resource, component)
        [+] return security.checkPermissionOnElements(component, tx, sriRequest, elements, operation)
```

**Comment by jgovaerts** [comment]
Fixed in 2.0.19
